HomeWorkLessons6Part2
Ruslan9222/HelloWorldProject pull request #13
Opened 2023-04-09 00:40 UTC by Ruslan9222

Я запутался немного, вроде что то работает, но не до конца, при помощи подсказок добавил HDD и RAM, сделать что бы можно было указать внешний или внутренний HDD так и не получилось(Хотя я это указал в классе)

2023-04-09 18:48 UTC, Pavel-Tsishkevich requested changes

2023-04-09 18:48 UTC, Pavel-Tsishkevich commented on src/by/ruslan/radevich/homework/lessons6/PC/Computer.java
> +    private int HDD;
Смотри, hdd и ram должны быть классов Hdd и Ram соответственно (теми что ты сделал)

2023-04-09 18:48 UTC, Pavel-Tsishkevich commented on src/by/ruslan/radevich/homework/lessons6/PC/Computer.java
> +    public void computer1(int price, String model) {
Вот это не надо, поясню в классе

2023-04-09 18:48 UTC, Pavel-Tsishkevich commented on src/by/ruslan/radevich/homework/lessons6/PC/Computer.java
> +    public void computer2(int price, String model, by.ruslan.radevich.homework.lessons6.PC.HDD HDD, boolean typeInstall, by.ruslan.radevich.homework.lessons6.RAM RAM) {
Это тоже не надо по той же причине

2023-04-09 18:48 UTC, Pavel-Tsishkevich commented on src/by/ruslan/radevich/homework/lessons6/PC/HDD.java
> +    public void typeInstall(boolean internal) {
Правильнее назвать installType

2023-04-09 20:47 UTC, Ruslan9222 commented on src/by/ruslan/radevich/homework/lessons6/PC/HDD.java
> +    public void typeInstall(boolean internal) {
все переделал, но все вообще отвалилось) Завтра приду пораньше)

2023-04-10 12:39 UTC, Pavel-Tsishkevich approved these changes

2023-04-14 20:17 UTC, merged