Lessons9HomeWork
Ruslan9222/HelloWorldProject pull request #19
Opened 2023-04-18 21:16 UTC by Ruslan9222

Need Help)

2023-04-21 12:38 UTC, Pavel-Tsishkevich requested changes

2023-04-21 12:38 UTC, Pavel-Tsishkevich commented on src/by/ruslan/radevich/homework/lessons9/IllegalCandidate.java
> +public class IllegalCandidate extends Voter{
смотри, кандидат и голосующий в плане родства никак не связаны, поэтому эти классы так не должны быть соединены, у них нет ни родителей ни детей

2023-04-21 12:38 UTC, Pavel-Tsishkevich commented on src/by/ruslan/radevich/homework/lessons9/IllegalCandidate.java
> +    private int Voter;
переменная с большой

2023-04-21 12:38 UTC, Pavel-Tsishkevich commented on src/by/ruslan/radevich/homework/lessons9/IllegalCandidate.java
> +    public void candidate2() {
метод должен начинаться с глагола, а тут еще и 2 какая-то в конце

2023-04-21 12:38 UTC, Pavel-Tsishkevich commented on src/by/ruslan/radevich/homework/lessons9/Main.java
> +       OfficialCandidate.vote = new OfficialCandidate();
уф, тут должна быть немного другая логика. Смотри, у кандидата должна быть переменная количество голосов, и есть отдельный класс Voter, который может голосовать, выбирая удобным ему способом или рандомом кандидата, за которого хочет проголосовать. Итак, в мейне ты в цикле создаешь 100 вотеров, и каждый из них голосует

2023-04-21 12:38 UTC, Pavel-Tsishkevich commented on src/by/ruslan/radevich/homework/lessons9/Voter.java
> +    static Voter vote;
вот как раз тут статик не нужен

2023-06-17 15:58 UTC, Ruslan9222 commented on src/by/ruslan/radevich/homework/lessons9/Voter.java
> +    static Voter vote;
Я ее победил) Не без помощи гугла конечно, но победил!) И весь вопрос был только 3х строчках
for (int i = 0; i < voters.length; i++) {
            voters[i] = new Voter();
            voters[i].vote(randomGenerator.nextInt(100) + 1, official, illegal, random);
        }

2023-06-19 11:31 UTC, Pavel-Tsishkevich approved these changes

2023-06-19 17:09 UTC, merged