Lessons11HomeworkPart1
Ruslan9222/HelloWorldProject pull request #23
Opened 2023-05-02 21:30 UTC by Ruslan9222

Привет, пока ничего не получается... Попробовал по разному, нужна помощь)

2023-05-07 20:55 UTC, Pavel-Tsishkevich requested changes

2023-05-07 20:55 UTC, Pavel-Tsishkevich commented on src/by/ruslan/radevich/homework/lessons11/ClassTask.java
> +    public static void thirdTask() {
смотри, здесь почти правильно, в двух других методах нет - что я прошу оставить тут - boolean check3 = condition.endsWith("1a2b");
            System.out.println(check3);
            if (check3) {
                System.out.println("here");
            } else throw new ExceptionClass("123", "1"); - вот эту часть
try/catch блок должен быть там, где ты вызываешь thirdTask

2023-05-08 16:19 UTC, Ruslan9222 commented on src/by/ruslan/radevich/homework/lessons11/ClassTask.java
> +    public static void thirdTask() {
Переделал, но есть один вопрос. Объясни простыми словами... Смотри, я создал исключение  throw new ExceptionClass("123", "1") Каково предназначение ("123", "1") вот этих полей в данном случае, или можно просто было как то создать исключение без конструктора что бы этих полей не было и был просто вывод сообщения на консоль. 
PS. Я понимаю что я сам эти поля вызвал с помощью конструктора, просто не понимаю для чего они в данном случае нужны

2023-05-08 22:04 UTC, Ruslan9222 commented on src/by/ruslan/radevich/homework/lessons11/ClassTask.java
> +    public static void thirdTask() {
Отправил вторую часть домашки, только тоже есть пару вопросов:
1) Я написал прямо в коде, я там использовал регулярное выражение, но мне кажется можно было иначе...
2) Не до конца понял последнюю часть домашки "WrongPasswordException и WrongLoginException - пользовательские классы исключения с двумя конструкторами – один по умолчанию, второй принимает сообщение исключения и передает его в конструктор класса Exception. Метод возвращает true, если значения верны или false в другом случае " Хотя все вроде работает...

2023-05-11 11:15 UTC, Pavel-Tsishkevich requested changes

2023-05-11 11:15 UTC, Pavel-Tsishkevich commented on src/by/ruslan/radevich/homework/lessons11/ClassTask.java
> +        } else throw new ExceptionClass("1", "11");
ну смотри, в целом правильно, но я б здесь в ошибку вставлял нужное сообщение, а потом в catch делал e.getMessage()

2023-05-13 17:04 UTC, Ruslan9222 commented on src/by/ruslan/radevich/homework/lessons11/ClassTask.java
> +        } else throw new ExceptionClass("1", "11");
Капец, как же все просто на самом деле, а я мучался несколько часов изначально...
А что по поводу второй части домашки?

2023-05-14 19:45 UTC, Pavel-Tsishkevich approved these changes

2023-05-14 19:46 UTC, Pavel-Tsishkevich commented on src/by/ruslan/radevich/homework/lessons11/ClassTask.java
> +    public static void thirdTask() {
давай вторую часть в классе обсудим, я ее тут не вижу, может там рассмотрю)

2023-05-16 21:41 UTC, merged