LessonsClass3 and home works part one
Ruslan9222/HelloWorldProject pull request #7
Opened 2023-03-28 23:37 UTC by Ruslan9222

Я немного все переделал, есть пару вопросов по домашним заданиям, счас кидаю просто потренироваться пользоваться Github

2023-03-29 09:26 UTC, Pavel-Tsishkevich requested changes
в целом все откомментировал, смотри, еще одно - привычнее называть FirstTask, SecondTask, а не TaskOne, TaskTwo

2023-03-29 09:26 UTC, Pavel-Tsishkevich commented on src/by/ruslan/radevich/homework/lessonsThird/TaskFour.java
> +package by.ruslan.radevich.homework.lessonsThird;
смотри, папки только с маленькими буквами, тут можно цифру, правильнее было бы наверное последнюю папку назвать lesson3

2023-03-29 09:26 UTC, Pavel-Tsishkevich commented on src/by/ruslan/radevich/homework/lessonsThird/TaskFour.java
> +        for (int i = number; i < 5; i++) ;
смотри, все как в классе - никаких ; после for, открывай скобки, тогда б увидел что твоя строчка 13 не в цикле

2023-03-29 09:26 UTC, Pavel-Tsishkevich commented on src/by/ruslan/radevich/homework/lessonsThird/TaskThree.java
> +            System.out.println(number += 7);
уф, скорее всего он не захочет вот так саут делать, надо разделить, или сначала писать number+=7; и потом саутом его выводить или наоборот, сначала саут, потом number+=7;

2023-03-29 09:26 UTC, Pavel-Tsishkevich commented on src/by/ruslan/radevich/homework/lessonsThird/TaskTwo.java
> +        for (int a = 1, b = 0; a + b <= number; b++) {
тут наверное не так понял задачу, имелось в виду, что если введено число 100 то сложить все числа от 1 до 100, а не пока сумма станет равна 100

2023-03-31 10:18 UTC, Pavel-Tsishkevich approved these changes

2023-03-31 17:18 UTC, Ruslan9222 commented
понял, сегодня переделаю и попробую ещё что нибудь решить

пт, 31 мар. 2023 г., 13:19 Pavel-Tsishkevich ***@***.***>:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Ruslan9222/HelloWorldProject/pull/7#pullrequestreview-1366671673>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6TZSFCGIBAJV7NCKVAWCFLW62VRZANCNFSM6AAAAAAWLHAEZU>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-04-03 15:59 UTC, merged